using System.Collections.Generic;
using EssSystem.Core.Presentation.UIManager.Dao.CommonComponents;

namespace EssSystem.Core.Application.SingleManagers.InventoryManager
{
    /// <summary>
    /// References to slot sub-components in one opened inventory UI.
    /// Generated by <see cref="InventoryUIBuilder.BuildPanelTree"/> and reused by refresh events.
    /// </summary>
    public class SlotUIRefs
    {
        public UIButtonComponent[] Buttons;
        public UIPanelComponent[] Icons;
        public UITextComponent[] Names;
        public UITextComponent[] Stacks;
        public UIPanelComponent[] SelectionRoots;
    }

    /// <summary>
    /// References used to update the left description panel after slot or info-tab clicks.
    /// </summary>
    public class DescUIRefs
    {
        public UIPanelComponent Icon;
        public List<UIPanelComponent> IconDecorations;
        public UITextComponent Name;
        public UITextComponent Stack;
        public UITextComponent Description;
        public string EmptyPlaceholder;
    }
}
